apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-stack
  namespace: infra-tools
  labels:
    app.kubernetes.io/name: mlops-stack
    app.kubernetes.io/component: ml-platform
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/DeadNord/hw-mlops.git
    targetRevision: lesson-8-9
    path: mlops-experiments/argocd/applications
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
