# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json

stages: [retrain, build, deploy]

variables:
  IMAGE: "$CI_REGISTRY_IMAGE/aiops-quality-service"
  DOCKER_TLS_CERTDIR: "" # для docker:dind
  GIT_STRATEGY: fetch
  GIT_DEPTH: "0"

.reuse-docker: &reuse-docker
  image: docker:24
  services:
    - name: docker:24-dind
      command: ["--tls=false", "--mtu=1460"]
  before_script:
    - |
      if [ -n "$DOCKERHUB_USERNAME" ] && [ -n "$DOCKERHUB_PASSWORD" ]; then
        echo "$DOCKERHUB_PASSWORD" | docker login docker.io -u "$DOCKERHUB_USERNAME" --password-stdin
      fi
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

retrain-model:
  stage: retrain
  image: python:3.11-slim
  script:
    - pip install -r app/requirements.txt
    - python model/train.py
    - mkdir -p artifacts && cp /model/model.pkl artifacts/ || true
  artifacts:
    paths:
      - artifacts/model.pkl
  # when: manual
  only:
    - branches # можно запускать вручную на любой ветке

build-image:
  stage: build
  <<: *reuse-docker
  # retrain — опционально: если был запущен, билд подхватит артефакты
  needs:
    - job: retrain-model
      artifacts: true
      optional: true
  script:
    - VERSION="$(cat VERSION)"
    - if [ -f artifacts/model.pkl ]; then echo "Model artifact found"; fi
    - docker build -f docker/Dockerfile.app -t "$IMAGE:$VERSION" .
    - docker push "$IMAGE:$VERSION"
  only:
    - branches

bump-helm-and-tag:
  stage: deploy
  image: alpine:3.19
  needs: ["build-image"] # деплой не начнётся без успешного билда
  before_script:
    - apk add --no-cache git openssh-client sed
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - |
      if [ -f "$DEPLOY_SSH_KEY" ]; then
        cp "$DEPLOY_SSH_KEY" ~/.ssh/id_ed25519
      else
        printf "%s\n" "$DEPLOY_SSH_KEY" > ~/.ssh/id_ed25519
      fi
    - chmod 600 ~/.ssh/id_ed25519
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_ed25519
    - ssh-keyscan -t rsa,ecdsa,ed25519 gitlab.com >> ~/.ssh/known_hosts
    - git remote set-url origin "git@gitlab.com:goit-neo/mlops-final-project.git"
    - git fetch --all --tags
    - git checkout -B "${CI_COMMIT_REF_NAME}"
    - git pull --ff-only origin "${CI_COMMIT_REF_NAME}" || true
  script: |
    set -e
    VERSION="$(cat VERSION)"

    sed -i -E 's/^( *tag:).*/\1 "'"$VERSION"'"/' helm/values.yaml
    sed -i -E 's/^( *appVersion:).*/\1 "'"$VERSION"'"/' helm/Chart.yaml

    git add helm/values.yaml helm/Chart.yaml
    git commit -m "chore: bump helm to ${VERSION}" || echo "nothing to commit"

    git tag -f "v${VERSION}" || true
    GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=yes' git push origin "HEAD:${CI_COMMIT_REF_NAME}"
    GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=yes' git push origin --tags
  only:
    - main
