apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aiops-quality-service.fullname" . }}
  labels:
    app: {{ include "aiops-quality-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "aiops-quality-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "aiops-quality-service.name" . }}
      annotations:
{{- with .Values.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 8000
        env:
{{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
{{- end }}
        readinessProbe:
          httpGet: { path: /health, port: 8000 }
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /health, port: 8000 }
          initialDelaySeconds: 10
          periodSeconds: 10
