apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aiops-quality-service.fullname" . }}
  labels:
    {{- include "aiops-quality-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aiops-quality-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aiops-quality-service.selectorLabels" . | nindent 8 }}
      {{- $loki := .Values.loki }}
      {{- if or .Values.podAnnotations (and $loki $loki.promtailScrape) }}
      annotations:
        {{- if and $loki $loki.promtailScrape }}
        loki.grafana.com/scrape: "true"
        {{- with $loki.tenant }}
        loki.grafana.com/tenant: {{ . | quote }}
        {{- end }}
        {{- $job := default (include "aiops-quality-service.fullname" .) $loki.jobName }}
        {{- $namespace := default .Release.Namespace $loki.namespace }}
        {{- $labels := default (printf "job=%s,namespace=%s" $job $namespace) $loki.labels }}
        loki.grafana.com/labels: {{ $labels | quote }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "aiops-quality-service.serviceAccountName" . }}
      containers:
        - name: fastapi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          ports:
            - containerPort: 8000
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}