apiVersion: v2
name: aiops-quality-monitoring
version: 0.1.0
appVersion: "1.0.0"
description: Umbrella chart for the AIOps monitoring stack (Loki, Promtail, Grafana)
type: application
dependencies:
  - name: loki-stack
    repository: https://grafana.github.io/helm-charts
    version: 2.9.11
  - name: promtail
    repository: https://grafana.github.io/helm-charts
    version: 6.11.5
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 6.59.4
