- job_name: aiops-quality-service
  honor_labels: true
  metrics_path: /metrics
  static_configs:
    - targets:
        - aiops-quality-service.aiops-quality.svc.cluster.local:8000
      labels:
        app: aiops-quality-service
        environment: production
