channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==23.2
  - pyyaml==6.0.2
  - scikit-learn==1.4.2
  - scipy==1.16.2
name: mlflow-env
