apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-quality-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/goit-neo/mlops-final-project.git
    targetRevision: main
    path: helm-monitoring
    helm:
      releaseName: aiops-quality-monitoring
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
