nameOverride: ""
fullnameOverride: ""

image:
  repository: registry.gitlab.com/goit-neo/mlops-final-project/aiops-quality-service
  tag: "0.1.5"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8000

env:
  - name: ENABLE_DRIFT
    value: "true"
  - name: LOG_LEVEL
    value: "INFO"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "8000"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceMonitor:
  enabled: true
  interval: 15s
  labels: {}
