replicaCount: 1

nameOverride: ""
fullnameOverride: aiops-quality-service

image:
  repository: registry.example.com/aiops-quality/service
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  - name: MODEL_PATH
    value: /app/model/artifacts/model.pkl
  - name: REFERENCE_DATA_PATH
    value: /app/model/artifacts/reference.npy
  - name: DRIFT_P_THRESHOLD
    value: "0.05"
  - name: LOG_LEVEL
    value: INFO
  - name: GITLAB_RETRAIN_TRIGGER_URL
    value: ""
  - name: GITLAB_RETRAIN_TRIGGER_TOKEN
    value: ""
  - name: GITLAB_RETRAIN_REF
    value: main

prometheus:
  enabled: true
  path: /metrics
  port: 8000

loki:
  enabled: true
  promtailScrape: true

nodeSelector: {}

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "8000"

podSecurityContext: {}
securityContext: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: aiops-quality.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

tolerations: []

affinity: {}
